Cleaned up quotes and if statements.

diff --git a/ping-host b/ping-host
--- a/ping-host
+++ b/ping-host
@@ -7,27 +7,27 @@
 
 
 # Help
-if [ -z $1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]
+if [ -z $1 ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]
 then
-  echo "Usage: ping-host HOST [HOSTN]..."
-  echo "Retuns 0 if the hosts respond to ping or 1 if any of them fail to respond."
-  exit 1
+  echo 'Usage: ping-host HOST [HOSTN]...' >&2
+  echo 'Retuns 0 if the hosts respond to ping or 1 if any of them fail to respond.' >&2
+  exit
 fi
 
 # What OS are we on?
-OS=`uname -s`
+OS=$(uname -s)
 
-if [ "$OS" = "SunOS" ]
+if [ "$OS" = 'SunOS' ]
 then
   # Solaris
-  PING="ping -t 10"
-  PING_SUFFIX_ARGS="1"
-  GREP_PATTERN="no"
+  PING='ping -t 10'
+  PING_SUFFIX_ARGS='1'
+  GREP_PATTERN='no'
 else
   # Linux / Mac
-  PING="ping -c 1 -W 1"
+  PING='ping -c 1 -W 1'
   PING_SUFFIX_ARGS=""
-  GREP_PATTERN="100%"
+  GREP_PATTERN='100%'
 fi
 
 # Hope for the best, prepare for the worst.
@@ -36,12 +36,11 @@ RETURN_CODE=0
 # Loop through the hosts provided on the command line.
 for HOST in $@
 do
-  PING_RESULT=$($PING $HOST $PING_SUFFIX_ARGS | grep $GREP_PATTERN | cut -d, -f3 | wc -l)
-  if [ $PING_RESULT -eq 1 ]
-  then
+  PING_RESULT=$($PING $HOST $PING_SUFFIX_ARGS 2>&1 | egrep "$GREP_PATTERN|unknown host" | cut -d, -f3 | wc -l)
+  [ $PING_RESULT -eq 0 ] || {
     RETURN_CODE=1
     echo "$HOST down"
-  fi
+  }
 done
 
 exit $RETURN_CODE
